/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h> // ×¢Òâ¸ÄÎª£º #include "jni.h"
/* Header for class NativeMethod */

#ifndef _Included_NativeMethod
#define _Included_NativeMethod
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     NativeMethod
     * Method:    sayHello
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_NativeMethod_sayHello
    (JNIEnv *, jobject);

    /*
     * Class:     NativeMethod
     * Method:    doCalc
     * Signature: (I)J
     */
    JNIEXPORT jlong JNICALL Java_NativeMethod_doCalc
    (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
